FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y nginx && \
    microdnf clean all && \
    rm -rf /var/cache/dnf

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /var/www/html/index.html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
